# Generated by Django 3.0.4 on 2020-05-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportSkills',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
