# Generated by Django 3.0.5 on 2020-05-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название мероприятия', max_length=120)),
                ('place', models.CharField(default='Место проведения', max_length=120)),
                ('date', models.DateTimeField()),
                ('people', models.CharField(default='Количество людей', max_length=120)),
                ('donnates', models.TextField()),
                ('comments', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id', '-timestamp'],
            },
        ),
    ]
