# Generated by Django 3.0.5 on 2020-05-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='emoji_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
